# Generated by Django 3.1.2 on 2021-04-17 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('array', 'array'), ('linklist', 'linklist'), ('stack', 'stack'), ('string', 'string'), ('matrix', 'matrix'), ('searching & sorting', 'searching & sorting'), ('binary tree', 'binary tree'), ('binary search tree', 'binary search tree'), ('greedy', 'greedy'), ('backtracking', 'backtracking'), ('heap', 'heap'), ('graph', 'graph'), ('tire', 'tire'), ('dynamic programing', 'dynamic programing'), ('bit manipulation', 'bit manipulation')], default='add a tag', max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('exmple', models.TextField(default='ex')),
                ('intro', models.TextField(default='abc')),
                ('code', models.TextField(default='abc')),
                ('body', models.TextField(default='abc')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='linux2.png', upload_to='profile_pics')),
                ('phone', models.CharField(default='1234567890', max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
