# Generated by Django 3.1.2 on 2021-04-19 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_addpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_posted']},
        ),
    ]
